version: '3'
services:
  state-producer:
    volumes:
     - ./state-producer:/app
    build: state-producer
    tty: true
  city-categories:
    volumes:
      - ./city_category:/app
    build: city_category
    tty: true
  store:
    volumes:
      - ./store:/app
    build: store
    tty: true
  queue:
    build: ./queue
    ports:
     - "15672:15672"
    tty: true
  scrape:
    volumes:
     - ./scrape:/scrape
    build: ./scrape
    tty: true
  elasticsearch:
    image: elasticsearch:5.6.7
    volumes:
     - ./elasticsearch/esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:5.6.7
    ports:
     - "5601:5601"

